# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Job": "01_Job.ipynb",
         "say_hello": "01_Job.ipynb"}

modules = ["Job.py"]

doc_url = "https://miguel8997.github.io/nbdev/"

git_url = "https://github.com/miguel8997/nbdev/tree/master/"

def custom_doc_links(name): return None
