# AUTOGENERATED! DO NOT EDIT! File to edit: 01_Job.ipynb (unless otherwise specified).

__all__ = ['Job', 'say_hello']

# Cell
class Job:
  def __init__(self):
    self.jobName=''
    self.jobRunVirtualMachine=''
    self.jobEnv=''
    self.jobStrategy=''
    self.jobSteps=''

# Cell
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'